name: "Code Review Analytics"
description: "Analyzes GitHub Pull Request review metrics"
inputs:
  GITHUB_TOKEN:
    description: "GitHub token to authenticate API requests"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt
      shell: bash

    - name: Run Python script
      run: python .github/actions/action/extract.py
      shell: bash
