name: "Code Review Analytics Action"

description: "A composite action to run extract.py and analyze GitHub code reviews."

inputs:
  github_token:
    description: "GitHub token to authenticate API requests"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        else
          echo "No requirements.txt file found"
        fi
      shell: bash

    - name: Run extract.py
      run: python extract.py
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
