name: "Code Review Analytics"
description: "Analyzes GitHub repository using extract.py and generates visual insights"
author: "eshabalaji"

inputs:
  github_token:
    description: "GitHub token to authenticate API requests"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt
      shell: bash

    - name: Run extract.py
      run: python extract.py
      shell: bash
