name: Run Code Review Analytics

on:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Analytics Action
        uses: ./.github/actions/action
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # optional — the action/script will fallback to GITHUB_REPOSITORY if you omit these:
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
