name: Run Code Review Analytics

on:
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install requirements
        run: |
          pip install -r requirements.txt || echo "No requirements.txt file"

      - name: Run Analytics Action
        uses: ./.github/actions/action
